name: smbuqenv
channels:
  - conda-forge
dependencies:
  - pip==23.2.1
  - cudatoolkit==11.7
  - pip:
      - torch==2.0.1
      - torchaudio==2.0.2
      - torchvision==0.15.2
      - tqdm==4.66.1
      - numpy==1.26.0
      - pandas==2.1.1
      - scikit-learn==1.3.1
      - matplotlib==3.8.0
      - uncertainty_toolbox==0.1.1
      - joblib==1.3.2
